CREATE TABLE "Headcount planning" (
    "Employee ID"                    VARCHAR(50),
    "StartDate"                      DATE,
    "Title"                          VARCHAR(100),
    "BusinessUnit"                   VARCHAR(100),
    "EmployeeStatus"                 VARCHAR(50),
    "EmployeeType"                   VARCHAR(50),
    "PayZone"                        VARCHAR(50),
    "EmployeeClassificationType"     VARCHAR(100),
    "DepartmentType"                 VARCHAR(100),
    "Division"                       VARCHAR(100),
    "DOB"                            DATE,
    "State"                          VARCHAR(50),
    "GenderCode"                     VARCHAR(10),
    "RaceDesc"                       VARCHAR(100),
    "MaritalDesc"                    VARCHAR(50),
    "Performance Score"              NUMERIC(5,2),
    "Current Employee Rating"        NUMERIC(5,2),
    "Survey Date"                    DATE,
    "Engagement Score"               NUMERIC(5,2),
    "Satisfaction Score"             NUMERIC(5,2),
    "Work-Life Balance Score"        NUMERIC(5,2),
    "Training Date"                  DATE,
    "Training Program Name"          VARCHAR(200),
    "Training Type"                  VARCHAR(100),
    "Training Outcome"               VARCHAR(100),
    "Training Duration(Days)"        INTEGER,
    "Training Cost"                  NUMERIC(12,2),
    "Age"                            INTEGER
);
